### PR TITLE
Beautified JS color to aid in fixing the enter bug

### PR DESCRIPTION
**Pull request by Pipe-to-Grep**

### CODE REVIEW

**Comment by Pipe-to-Grep** [comment]
Yes, don't worry about it. I just needed it to read it. I didn't realize I could do it with chrome anyway.

**Comment by Pipe-to-Grep** [comment]
Speaking of debugging, removing the js button using inspect element fixed the issue. This means that when you hit enter, chrome auto jumps to the button and hits it.

**Comment by CameronSamuels** [comment]
You mean removing the font color button? Don't we want that?

Or am I understanding wrong?

**Comment by Pipe-to-Grep** [comment]
I removed the font color to see if there was some kind of listener in jscolor. By removing it, we can see that there is an issue with hitting enter and the browser. I'm looking into it.

**Comment by Pipe-to-Grep** [comment]
I fixed it!!!!

**Pull request closed without merging**
