### PR TITLE
Updated contributing file

### PR DESCRIPTION
**Pull request by Pipe-to-Grep**
Renamed contributing file, plus added section in readme.

### CODE REVIEW

**Comment by CameronSamuels** [comment]
We can merge into a Google Analytics branch and not that master, so don't merge yet.

**Comment by Pipe-to-Grep** [comment]
I included a few more commits regarding contributing and readme

**Comment by CameronSamuels** [comment]
These commits should've been on a separate pr. We might want to close this pr and create a separate one for the contributing guidelines commits and another for the GA.

Make sure to name the branches something good instead of `Pipe-to-Grep-patch-1`. Thanks!

**Comment by Pipe-to-Grep** [comment]
i will make separate ones. i realised what i had done afterwards. i still dont know how to test the GA.

**Comment by CameronSamuels** [comment]
Check my issue #72 comment with a link of how to test GA locally.

**Comment by Pipe-to-Grep** [comment]
I messed up the branch, so just approve, merge, and close. I'll uncomment and add GA functionality in a GA branch

**Pull request merged**
