### PR TITLE
Google analytics - events

### PR DESCRIPTION
**Pull request by Pipe-to-Grep**

### CODE REVIEW

**Comment by Pipe-to-Grep** [comment]
@CameronSamuels This should do it!

**Comment by Pipe-to-Grep** [comment]
Once you review, I'll make a jquery-cleanup branch and remove at least one line I found. @CameronSamuels

**Comment by Pipe-to-Grep** [comment]
@CameronSamuels I cleaned it up per your requests

**Comment by Pipe-to-Grep** [comment]
I won't delete the branch, so just commit with changes here

**Comment by CameronSamuels** [comment]
I’ll just make a separate pr with changes

**Pull request merged**
